apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  labels:
    app: nginx-pods-label
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["tail"]
      args: ["-f", "/dev/null"]
